### ISSUE TITLE
Unable to connect from www/index.html to phonegap in my android mobile.

### ISSUE THREAD

**Issue by giridhar69** [phonegap/phonegap-app-desktop#268]
![screenshot 2015-01-09 13 59 12](https://cloud.githubusercontent.com/assets/10461135/5677131/06578dfc-9808-11e4-9d35-16cff6a23221.png)
![picture003](https://cloud.githubusercontent.com/assets/10461135/5677134/167dcfde-9808-11e4-8aae-f43ca17cd4a4.jpg)

**Comment by hermwong** [comment]
@giridhar69,

Could you provide more details regarding your issue?

Based on your first screenshot, you won't be able to connect using a desktop browser because the desktop browser doesn't trigger a `deviceready event` so the PhoneGap app will stay stuck on `connecting to device`.

Your second screenshot looks like your mobile device has correctly loaded the default example app that is generated by the create new project workflow in the PhoneGap Desktop App.

**Comment by giridhar69** [comment]
Thanks hermwong, there is a small problem with the network connection for a lot of time while i was developing my first app using phonegap, after posting this problem i checked everything out and found problem with my network connection, now its working superb! I love this technology. Thanks for your reply.
![10413342_596122127184905_700591217491890105_n](https://cloud.githubusercontent.com/assets/10461135/5690712/d8ffa08a-98c3-11e4-9830-07956e31452c.jpg)
I tested this by changing header in index.html and image link in css.

**Comment by AmitLomte1** [comment]
I am using the phonegap desktop app but my doesnt get connected to the desktop app it will only blinks in the black shade as connecting to device but does not get connected please help me
