### ISSUE TITLE
Orientation not working on IPhone 5

### ISSUE THREAD

**Issue by Komrod** [phonegap/phonegap-app-desktop#280]
Hi,
I have some problems with the orientation on my IPhone5 when I use the PhoneGap Developper App. Basically, it's always locked on "portrait" mode. I changed the settings in my config.xml but nothing seems to work. Even when orientation is set to "default" mode, nothing happen when I tilt my phone.

Here is what I use in my config.xml file:
[preference name="Orientation" value="landscape" /]

On Iphone 5, Ios 8.1.2, PhoneGap Developer App 1.4.0 on Win7

It works when I build my app on Android and use it on my android phone but not with the PhoneGap Developper App on my Iphone. Other apps on my Iphone are working well, so orientation detection is not broken.

I'm developping an app in lanscape mode and I can't use Phonegap dev app!
Hope you guys can fix this.

Thanks

**Comment by hermwong** [comment]
The PhoneGap Developer App should be able to preview apps that use [landscape orientation](https://github.com/phonegap/phonegap-app-developer/issues/107).

It seems that the issue may have been reintroduced into the PG-Developer App since the initial fix. 

We've logged your issue into the [PhoneGap Developer App issue tracker](https://github.com/phonegap/phonegap-app-developer/issues/266).

**Comment by surajpindoria** [comment]
This should now be fixed in the developer app. Closing this, please reopen if it is still an issue.
