### ISSUE TITLE
200 /__api__/autoreload

### ISSUE THREAD

**Issue by 818633** [phonegap/phonegap-app-desktop#339]
Hii,
After connect to phonagap server keep fire the "200 /__api__/autoreload" commands and stuck 

![image](https://cloud.githubusercontent.com/assets/12038744/7238241/8235f404-e7a9-11e4-8fc5-88ea2fce2289.png)

**Comment by hermwong** [comment]
Would you be able to provide step by step instructions for me to reproduce this issue?

**Comment by chintusoni** [comment]
Yeah I'm facing the same problem. When i run the server it fires [phonegap] 200 /__api__/autoreload.

**Comment by jcpenuela** [comment]
Hi all!. I'm having this same issue, but I'm running the server in command line in linux.

**Comment by hermwong** [comment]
The auto reload is one of the features of the PhoneGap Developer app, it continuously auto reloads the content being previewed so that it will always display the most up to date version of your app.

If you happen to edit your project while it is being previewed in the PhoneGap Developer app, your edits will be displayed within the PhoneGap Developer once you have saved your edits.

**Comment by jcpenuela** [comment]
Thanks hermwong. Ok, it have sense. Nonetheless a way to hide the continuous message would be really great. Have a good weekend.

**Comment by elovattibr** [comment]
phonegap serve | awk '!/autoreload/' 
it will ignore lines with this text;
