### ISSUE TITLE
Plugins not responding

### ISSUE THREAD

**Issue by murliatdure** [phonegap/phonegap-app-desktop#343]
Hello,
Phonegap core plugins are responding as expected.. But soe of teh third party plugins are not working
E.g. - Toast, OneSignal ..

<gap:plugin name="nl.x-services.plugins.toast" />
<gap:plugin name="com.onesignal.plugins.onesignal" />

Can you please assist em on the same.

**Comment by hermwong** [comment]
@murliatdure,

Third party plugins are not supported in when previewing apps in the PhoneGap Developer App. Currently we only support the PhoneGap core plugins when previewing apps in the PhoneGap Developer App.

**Comment by murliatdure** [comment]
Thanks alot .. Actually this is something a lifeline feature for developing and testing the apps on-the-fly instantly.. without building the app.

Would be great if somesort of tricks are shared for handling the third party plugins too.

Thanks,

**Comment by hermwong** [comment]
@murliatdure We're actually trying to determine the best way to solve this issue (we don't have an ETA).

Currently the `PhoneGap Developer App` bundles all of the core `PhoneGap Plugins`, which is why only core plugins are supported. We can not bundle all 3rd party plugins since it would not be a scalable solution.
