### ISSUE TITLE
Please make the link to the local server clickable

### ISSUE THREAD

**Issue by jorisw** [phonegap/phonegap-app-desktop#352]
Right now I have to manually type the 192.168.1.X:3000 address into my browser. Copying the link doesn't work either as the app has no Edit menu on Mac at least.

**Comment by hermwong** [comment]
If you're trying to use a desktop browser to preview your project, the project will not load since the desktop browser will never trigger a `deviceready` event.

The served url is meant to be used by the PhoneGap Developer App and possibly with the web browser on your mobile device (I'll need to confirm).

**Comment by hermwong** [comment]
We will soon be adding the desktop web browser as a platform that developers can use to preview their apps. The IP addresses will be updated to launch the web browser to preview the project on the local server.
