### ISSUE TITLE
Sometimes code seems to cache

### ISSUE THREAD

**Issue by markjsb** [phonegap/phonegap-app-desktop#371]
After making some changes to the JS in the code there was no change after transferring to the phone, I added console.log messages just to check, again these did not show up. 

To make it work I had to quit on both desktop and phone to force the update to send across, it worked exactly as it should after restarting. This seems to be an intermitting bug, it has happened a few times.

It is a problem having to restart because this slows development time right down. 

Mac OS 10.10.3, Android 5.1.1, Phonegap desktop 0.1.7

**Comment by markjsb** [comment]
EDIT - I have been experimenting with just stopping the server and starting it on the desktop App, that doesn't solve it. However if I quite the mobile app and restart then the code is a complete refresh, but this is still very slow having to stop and start the mobile app each time there's a change in code. Using the earlier desktop App didn't have this problem.

**Comment by hermwong** [comment]
Are you using PhoneGap Developer 1.5.2 on your mobile device?

**Comment by markjsb** [comment]
According to Google Play, yes

**Comment by markjsb** [comment]
And just checked my settings on phone, yes 1.5.2

**Comment by hermwong** [comment]
The 1.5.3 release of the PhoneGap Developer app should fix this issue.

The issue was being caused in [`phonegap-plugin-contentsync`](https://github.com/phonegap/phonegap-plugin-contentsync/issues/33) dependency used by the PhoneGap Developer App.

The changes can be seen [here](https://github.com/phonegap/phonegap-app-developer/commit/b30f866e6d1f9cd92c1e2ebbb792081f76ba6044).
