### ISSUE TITLE
"nwjs Helper" processus use 100% CPU

### ISSUE THREAD

**Issue by cidmcflow** [phonegap/phonegap-app-desktop#373]
Hello,
I use the last version of PhoneGap Desktop on my MacBook Pro. But when I launch PhoneGap the processus "nwjs Helper" use 100% of CPU.
My Project has a lot of files and it is for 2 platforms (iOS : 60Mo and Android : 60Mo)
Regards
Florian

**Comment by hermwong** [comment]
Would you be able to provide the following info:

What version of OSX are you running on your MacBook Pro?


Does your project load properly in the PhoneGap Desktop if you wait for a few minutes or does the PhoneGap Desktop crash?

Are you using a firewall, anti-virus or disk encryption software?

**Comment by cidmcflow** [comment]
I use OS X 10.9.5
After few minutes PhoneGap Desktop doesn't crash but fans are very noisy
No I am not using a firewall, anti-virus or disk encryption

**Comment by RmACK123** [comment]
I just found this issue while searching for what nwjs helper is because my Macbook Pro has slowed to a crawl due to nwjs Helper consuming 16GiB and causing OS X to compress my RAM content and swap like crazy. 

I have been running Phonegap 5.0.0-0.28.1 on OS X 10.10.3 continuously for several days as well as Xcode, Netbeans & Photoshop. Soon after closing the Phonegap GUI app, Activity monitor showed a massive drop in "memory pressure".

**Comment by olimortimer** [comment]
I have the same issue on my iMac (2.5 GHz Intel Core i5).

OS X Yosemite 10.10.3
PhoneGap Desktop 0.1.9

On first load, PhoneGap Desktop only seems to use between 1-3% CPU.  However, I leave my Mac on overnight, and all programs still running, and this morning 'nwjs Helper' was using 115% CPU over a CPU time of 25:25:35:16.

**Comment by hermwong** [comment]
Most likely related to: https://github.com/nwjs/nw.js/issues/2723

It was fixed in NWJS 0.12.2.

We will be updating to NWJS 0.12.3 for PhoneGap Desktop 0.1.11.
