### ISSUE TITLE
Does not show error message if port in use

### ISSUE THREAD

**Issue by deslee** [phonegap/phonegap-app-desktop#528]
I tried to open a project while port 3000 is in use, and nothing happened. At first I thought that the application was broken, but when I terminated the other server that's binding to port 3000, the application finally started to respond.

**Comment by hermwong** [comment]
That's odd. It should show an error when the port is in use.

<img width="455" alt="screen shot 2016-01-21 at 11 36 16 am" src="https://cloud.githubusercontent.com/assets/107754/12492070/4aa684fa-c033-11e5-843d-bfb1c571d8a7.png">

Would you be able to provide more information regarding your local setup and network?

**Comment by Gennttii** [comment]
same error...

**Comment by deslee** [comment]
I didn't get the listen EADDRINUSE error in the PhoneGap GUI application.

Here's some more info:
I was using the `phonegap serve` server on a CLI, and left it on when trying to use the Phonegap GUI,

**Comment by hermwong** [comment]
@deslee Both the CLI and PhoneGap Desktop use port 3000 (by default) for their serve feature. If you have started `phonegap serve` on the CLI and then started using PhoneGap Desktop without shutting down the CLI's server you will run into a conflict unless you've configured the CLI and the PhoneGap Desktop so that they don't use the same port.

**Comment by surajpindoria** [comment]
Going to close this due to inactivity, we have also updated the EADDRINUSE message to be more helpful along with a link to some docs.
