### ISSUE TITLE
Unable to connect desktop

### ISSUE THREAD

**Issue by Wingyau** [phonegap/phonegap-app-desktop#592]
Unable to connect the pg-desktop keep on timing out, but the pg-developer (mobile) can connect to the server.

On company computer running on netwrok - which produces multi ip addresses

**Comment by hermwong** [comment]
@Wingyau, if you could provide the following information it would help me troubleshoot:

PhoneGap Desktop version / PhoneGap CLI version
PhoneGap Mobile App version
Mobile devices & Mobile OS version
Computer OS version
network type (home/corporate)
computer / network security (firewall / anti-virus / disk encryption)
are you using VMs on your computer?
do you have multiple network adapters (or virtual network adapters)
are you using VPN?

**Comment by Wingyau** [comment]
cheers hermwong...

response:
PhoneGap Desktop version / PhoneGap CLI version: PG-Desktop V: 0.2.3  \ PG-CLI V: unable to install (possibly to do with our corporate network)
PhoneGap Mobile App version: Current version: 1.6.0
Mobile devices & Mobile OS version: Nexus 5P - Andriod V: 6.0.1
Computer OS version: Windows 7 Professional
network type (home/corporate): Corporate
computer / network security (firewall / anti-virus / disk encryption): HP / Firewall
are you using VMs on your computer? NO
do you have multiple network adapters (or virtual network adapters): YES
are you using VPN? YES

My problem is to do with corporate network - access rights...if you can find alternative that will be much appreciated if not thank you for looking into this and for your time.

**Comment by hermwong** [comment]
From the info you've provided there are a few things that could be preventing the PhoneGap Mobile App from connecting with the PhoneGap Desktop.

Here are the potential issues based on your configuration:

1. Corporate network - we've found that many corporate networks have security policies that prevent the zip file being served from the PhoneGap Desktop to the PhoneGap Mobile App.
1. Firewall - could potentially be blocking the port being used by the server created by PhoneGap Desktop and also could be blocking the zip file being served from the PhoneGap Desktop to the PhoneGap Mobile App.
1. VPN - same issues with corporate network.

Unfortunately, we don't have a solution for corporate network access rights since we don't have the ability to change the access rights on corporate networks.
