### ISSUE TITLE
Existing project error on local path but no local path entered yet

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-app-desktop#599]
Using **pre-release 0.3.0**

I was creating a project and I skipped the local path field and typed in a name first, but I received this error rather than the typical error where you must enter a local path:

![image](https://cloud.githubusercontent.com/assets/359935/14612074/6598fa84-0563-11e6-9254-d7a4e4c28c8f.png)

Not sure if related to [issue 598](https://github.com/phonegap/phonegap-app-desktop/issues/598 ) or not but happened in same session a couple projects after that error.

**Comment by hermwong** [comment]
I was able to reproduce this issue by following a certain workflow.

1. cause `The chosen folder already contains a PhoneGap project` error by selecting a project folder that already contains an existing PhoneGap project
1. click `Cancel` / choose another folder & `Create project`
1. start the workflow to create a new project
1. this time SKIP the project folder selection
1. enter a project name
1. focus out of the project name field
1. the `The chosen folder already contains a PhoneGap project` error displays instead of the `You must choose a local path` error.

It looks like the error message is getting set when the first error is caused but never gets reset on the second time through, so the wrong error message is being displayed to the user.

![screen recording 2016-04-18 at 11 45 am](https://cloud.githubusercontent.com/assets/107754/14615770/229dcdb0-055c-11e6-999a-dbafdc7aee58.gif)
