### ISSUE TITLE
R&D: Desktop Installers

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#63]
The PhoneGap-GUI should be packaged into a desktop installer such as .img on Mac and setup.exe on Windows.

**Comment by hermwong** [comment]
Possible solutions for creating Mac installers:
http://sourceforge.net/projects/macinstallerapp/
http://www.macupdate.com/app/mac/34613/packages

**Comment by mwbrooks** [comment]
Yesterday, I had the opportunity to chat with @jahoni about the installer experience on OS X. From our chat, she had a few questions that I've looked into and I'll summarize here:

__Show me two good examples__

Evernote
![screen shot 2015-01-16 at 2 22 00 pm](https://cloud.githubusercontent.com/assets/21328/5785407/143a3ea0-9d8b-11e4-9ef0-f8bfaad8e36e.png)

Dropbox
![screen shot 2015-01-16 at 2 22 08 pm](https://cloud.githubusercontent.com/assets/21328/5785410/19b1583c-9d8b-11e4-969e-ad2699779656.png)

__What is the standard window size of a mounted image (.dmg)?__

As far as I've found, Apple does not encourage a standard size. Both Dropbox and Evernote use custom sizes.

I created a default DMG using the Apple Disk Utility. When I found the image, the window size is 1540x810 (retina) or 770x405 (non-retina). Here is what it looks like:
![screen shot 2015-01-16 at 2 09 05 pm](https://cloud.githubusercontent.com/assets/21328/5785419/3a3a810a-9d8b-11e4-8095-65ca1a19edd3.png)


__Can the window resize be disabled?__

No, the mounted image opens a Finder window that cannot be locked down in any way.

As you can see, the user can resize the window however they wish:
![screen shot 2015-01-16 at 2 24 08 pm](https://cloud.githubusercontent.com/assets/21328/5785426/5866ce72-9d8b-11e4-8537-5893e7d7bb3e.png)
![screen shot 2015-01-16 at 2 23 56 pm](https://cloud.githubusercontent.com/assets/21328/5785434/614733d8-9d8b-11e4-9f1f-f8cdcabc321e.png)

__Tell me about the background image.__

The mounted image is simply a customized Finder window. You can mount any DMG (Evernote or Dropbox for example), open the window, and click `View -> Show View Options` to see the customizable properties.

The background image is very limited. You can define an image, but you cannot define how it is displayed (tiled, stretched, etc) or the image resolution. The image resolution is particularly important. I've recently noticed that all DMG installers have non-retina background images - I believe this is because the image dimensions cannot be specified and a non-retina image must be used to look proper on non-retina displays.

It's safer to use a flat color.

__Tell me about the icons__

You can position and size the icons, but the user can always change that. Each mounted image has a slider in the top-right corner. This allows the user to scale the icons. This can also result is strange rendering issues when you are creative with the background - for example, checkout what happens with Evernote icon glow:

![screen shot 2015-01-16 at 2 24 55 pm](https://cloud.githubusercontent.com/assets/21328/5785443/7565192a-9d8b-11e4-893f-2b77a97edbc8.png)

__Can we show a EULA?__

Yes, it looks as though we can define the text to shown. The EULA will be shown before the image is mounted and the user must agree to it:
![screen shot 2015-01-16 at 2 21 55 pm](https://cloud.githubusercontent.com/assets/21328/5785453/8e55c506-9d8b-11e4-9f27-8a15d77aa0a8.png)

**Comment by purplecabbage** [comment]
![screen shot 2015-01-17 at 1 00 01 am](https://cloud.githubusercontent.com/assets/46134/5809843/2e65d604-9ff2-11e4-825b-18d4d20d87dd.png)

![screen shot 2015-01-17 at 1 00 24 am](https://cloud.githubusercontent.com/assets/46134/5809846/37aa6234-9ff2-11e4-9624-727805abca11.png)

**Comment by hermwong** [comment]
Inno Setup [sample code](http://www.vincenzo.net/isxkb/index.php?title=Adding_a_rule_to_the_Windows_firewall) to disable Windows firewall prompt.

**Comment by jahoni** [comment]
@mwbrooks - thanks for looking into all those specifics. I'm partial to the visual design and content of the Evernote example.

Let I need to step in to create the visual assets, or if @GarthDB will be taking the reins.
