### ISSUE TITLE
PG-CLI create command in Desktop

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#631]
The `create` API seems to work in Electron when using `shell.exec` to invoke `phonegap create` but when we try using `phonegap.create()` API the `create` function fails in Electron.

**Comment by mwbrooks** [comment]
The [current implementation spawns a child process of the PhoneGap CLI](https://github.com/phonegap/phonegap-app-desktop/blob/8e895d24a2055f9dbee8a147c2a230b868281365/www/js/project-create-open-handlers.js#L143-L161), which results in the following error:
```bash
env: node: No such file or directory
```

This is because the environment and specifically `PATH` is inherited from the Electron process. When an Electron app is launched on OS X, it has a self-contained and minimal environment setup. The `PATH` does not inherit from the user's path.

We can workaround this issue by programmatically invoking the PhoneGap create method using the Node.js API. However, the same error will occur when the PhoneGap CLI shells out to the Cordova CLI.

We can workaround the Cordova CLI issue by rewriting the PhoneGap CLI to programmatically invoke the Cordova CLI. In the past, the Cordova CLI has been very unreliable as a node module (e.g. promises not firing), but it is improving. Unfortunately, the same error will continue to crop up anytime Cordova tries to spawn a process to execute a platform script. This happens when the browser platform is added when serving a project.

**Comment by mwbrooks** [comment]
Commit e3a30fb can reliably spawn a node process / script from Electron.

This above approach is inspired by Atom. I noticed that that Atom has an API called [`BufferedNodeProcess`](https://atom.io/docs/api/v1.7.4/BufferedNodeProcess) that allows you to spawn a node process. From there, I explored the Atom [source code for `BufferedNodeProcess`](https://github.com/atom/atom/blob/master/src/buffered-node-process.coffee#L38) and [`BufferedProceess`](https://github.com/atom/atom/blob/master/src/buffered-process.coffee#L48). With a few tweaks, I was able to output the version of node in Electron (`5.x`) and invoke the PhoneGap CLI as a spawned process. This means that it fixes the following error:

```bash
env: node: No such file or directory
```

The next problem is that the Cordova CLI cannot be found from inside the PhoneGap CLI. This is because Electron does not include the local `/node_modules/.bin/` directory. I'll patch this next.

**Comment by mwbrooks** [comment]
I've patched the PhoneGap CLI to find the Cordova CLI binary.

- [PhoneGap CLI issue](https://github.com/phonegap/phonegap-cli/issues/595)
- [PhoneGap CLI branch](https://github.com/phonegap/phonegap-cli/tree/595-desktop-support)

We now receive the same node environment error as before, but when the Cordova CLI is invoked:
```
env: node: No such file or directory
```

**Comment by surajpindoria** [comment]
This has been fixed now with the bundling of node
