### ISSUE TITLE
Desktop App and PayPal plugin in preview

### ISSUE THREAD

**Issue by bigz90210** [phonegap/phonegap-app-desktop#641]
I'm trying to use PhoneGap Desktop with a Mobile app and test PayPal plugin to preview my application. However, I'm getting an error message "PayPalMobile is not defined" as it fails when executing JS line PayPalMobile.init(clientIDs, app.onPayPalMobileInit) from index.js where this method PayPalMobile.init is defined in cdv-plugin-paypal-mobile-sdk.js.
Does this work for anyone? Any suggestions? TY

**Comment by surajpindoria** [comment]
This is happening because the PhoneGap Developer app does not include the PayPal plugin. In order to get this working you would need to create a [custom build](https://github.com/phonegap/phonegap-app-developer#adding-custom-plugins) of the developer app that has the PayPal plugin and this should work fine

**Comment by bigz90210** [comment]
Thanks for your reply.
I did some research and in the Preview mode, PhoneGap Developer app only supports the core cordova plugins, whereas PayPal is a third party plugin and it is not supported in the Preview mode. However, it does work when I do a PhoneGap Build Service. Your link is useful if one were to include a custom plugin which is not a core or 3rd party plugin.
