### ISSUE TITLE
Error on create first project: Selected folder doesn't contain a config.xml file.

### ISSUE THREAD

**Issue by williamnerdy** [phonegap/phonegap-app-desktop#648]
On create a project show message "Selected folder doesn't contain a config.xml file.
", my OS is Windows 7.

**Comment by lezhnev74** [comment]
Same thing on MAC EL Captain 10.11.5

**Comment by erickmonteiro** [comment]
same problem in Windows 10

**Comment by hermwong** [comment]
Could you provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. is your network using a proxy?
7. computer / network security (firewall / anti-virus / disk encryption)
8. are you using VMs on your computer?
9. do you have multiple network adapters (or virtual network adapters)
10. are you using VPN?

**Comment by mkikmail** [comment]
Same thing on Windows 10 pro 64bit.
Here the Details:
Computer:
Phonegap Desktop Version Version 0.3.3 (same with Version 0.3.2)
Operating System Windows 10 pro 64bit, Version 1511
Home Network, no Proxy involved
Firewall and anti-virus switched-off
Phonegap started under Administrator account 
Phonegap Mobile App not used because the Project could not be created correctly
Mobile Device Samsung Galaxy S5 with Android 
There are two VMware Network Adapters but which are deactivated, VMware is installed, but not started. I stopped all processes from VMware in Task Manager.
I am using VPN, but it is nit started / no cennection in use.

Mobile:
not interesting because the failure already happens when I want to create a new Project.

what happens:
during Installation Phonegap creates a folder under account .../.cordova/lib/WWW/com.phonegap/HelloWorld/master/ which includes files with 10 files plus one further folder .../.cordova/lib/WWW/com.phonegap/HelloWorld/master/template_src with 3 files plus one further folder .../.cordova/lib/WWW/com.phonegap/HelloWorld/master/template_src/WWW/ with 5 folders css, img, js, res, spec and 4 files config.xml, Icon.png, index.html and spec.html. The 5 folders contain other files / folders.
When I create a new Project Phonegap creates a new folder according to the Project name. This folder contains 4 empty folders .cordova, hooks, platforms plugins, no files at all.
As I understood, phonegap should copy the files from the master folder .../.cordova/lib/WWW/com.phonegap/HelloWorld/master/template_src/WWW/ to the Project folder. But this does not happen.

**Comment by mkikmail** [comment]
I tried again on a different PC (also Windows 10 pro 64bit, but without any VMware and VPN), and the result is exactly the same as describe above.
-> VMware and VPN is not the problem.

**Comment by hermwong** [comment]
One thing you could try would be to reset PhoneGap Desktop's template cache by deleting the `.cordova` folder at the following locations:

On Mac:

`/Users/<username>/.cordova`

On Windows:

`C:\Users\<username>\.cordova`

**Comment by mkikmail** [comment]
I tried this, but no changes.
When I create a new Project the identical Folder .cordova with same content as before is created again.
The new created project folder and the four subfolders (.cordova, hooks, platforms, plugins) do still contain no files at all.

Where can I download a "master project" / empty Project / HelloWorld Project so that I can create my own starting point.

**Comment by mkikmail** [comment]
I found this description in thread #584 
Thanks again for your patience and providing the information that we required to troubleshoot this issue.

@devgeeks was able to quickly resolve the issue with the information provided.

To get the fix to work on your computer's you'll need to reset your Local Storage and also reset PhoneGap Desktop's template cache.

To reset the Local Storage you'll need to delete the Local Storage folder used by PhoneGap Desktop at the following locations:

On Mac:

 ~/Library/Application Support/PhoneGap/Local Storage 

On Windows:

 C:\Users\<Windows User Name>\AppData\Roaming\PhoneGap\Local Storage 

Next you'll need to reset PhoneGap Desktop's template cache by deleting the  .cordova  folder which can be found at the following locations:

On Mac:

 /Users/<username>/.cordova 

On Windows:

 C:\Users\<username>\.cordova 
 ************************************************************************************************
I tried These suggestions but no Change at all.  The new created project folder and the four subfolders (.cordova, hooks, platforms, plugins) do still contain no files at all.

**Comment by hermwong** [comment]
Thanks, we'll take a look and see if we can find out is happening.

**Comment by hermwong** [comment]
Here is the latest update on this issue: https://github.com/phonegap/phonegap-app-desktop/issues/584#issuecomment-233056416

**Comment by hermwong** [comment]
We've made a fix to the template, however you'll need to reset your template cache by deleting the `.cordova` folder.

One thing you could try would be to reset PhoneGap Desktop's template cache by deleting the .cordova folder at the following locations:

On Mac:

`/Users/<username>/.cordova`

On Windows:

`C:\Users\<username>\.cordova`

**Comment by Delevop** [comment]
Hi; are we waiting for 0.3.4 to receive the fix from yourselves, or is there a workaround? Thanks again..

**Comment by hermwong** [comment]
@Delevop there wasn't a new release of the PhoneGap Desktop app. The fix was made to the template which is used by the PhoneGap Desktop.
