### ISSUE TITLE
Review Template Branch UI

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-app-desktop#675]
- Review the new spinner/fade effect added to indicate the create is in process (related to issue #651). See the associated video showing it [here](http://recordit.co/NYDKnCyNYL)
- Review the template branch UI overall for consistency

UX related question:
 1. Default the local directory to the last one chosen? We could store it using Local Storage. We could also default their first project's initial path to the users directory. Thoughts?

**Comment by jahoni** [comment]
Sweet! Things are looking good.

1. I would LOVE LOVE LOVE to see the "Local Path" field populated with the last directory selected (as @hollyschinsky has suggested above). That was the intent in the design (mock-up below), but don't think it was available at the time of initial implementation. If it is now, awesome.
![desktop-app_0010_add-create-step2](https://cloud.githubusercontent.com/assets/178345/17634029/549e2ca4-6085-11e6-8e6d-11aa130c52dc.png)

2. Is it me, or does the drag and drop functionality not "work"? The intention was that users could drag a folder into the app, and a new project would be created from that folder....kinda like what happens in Ghostlab ([view a screencap](https://www.dropbox.com/s/nlegnt0rahzsy3t/ghostlab-dragndrop.m4v?dl=0)). Right now, users can drag a folder into the Desktop app, but nothing really happens (other than it seeming that the "+" button has been hit) ([view a screencap](https://www.dropbox.com/s/y37zeawsdmc4x2w/phonegapdesktop-dragndrop.m4v?dl=0)) My suggestion goes like this: if we can actually create a new project by dragging in a folder let's keep it, if we can only do what we're doing now - let's get rid of it.

3. I'm not super happy with the transition between clicking the "Create new PhoneGap project..." link and the appearance of the template menu. There is a weird dissonance between the sliding back/out/left of the create menu, and the sliding down of the template menu. ([View a quick screencap of the transition I'm talking about here](https://www.dropbox.com/s/udz9w0g58k8b5wh/create-transition.m4v?dl=0)). If I manually scrub through the recording, I believe what is happening is that the template menu is sliding down "behind" the create menu, and the timing of the transitions isn't quite right. I *think* what I'd like to see is the template menu slide down, over top of the create menu, and that any transition out of the create menu be timed/obscured so that it isn't visible. This might require a bit of tweaking and/or a quick face to face to talk it out. 

4. The progress indicator isn't working well (because it isn't very visible) on the "creating app" screen. I'd like to suggest a couple of things: darken the colour of the modal overlay to about 80% transparent black, and change the colour of the indicator to white. Also - can we add helpful wording like "Loading PhoneGap Desktop..." and "Creating Project..." to the screens where the progress indicator appears?

A few visual design related items:
- There should be more space between the "|" (pipe separator) and the surrounding characters in the "STEP 1 of 2  I  SELECT A TEMPLATE" title.
- The radio buttons should be aligned (left justified) to the other items..right now the list is indented about 20px.
- The first item in the radio button list should be selected, which is the generally accepted pattern for this type of component. When I opened it, the second item (hello-world) was selected.
- I'd like to see friendly names (Hello World) used instead of computer generated names (hello-world) for the templates, as shown in the mock-up.
- I believe the order of the templates should be what is outlined in the mock-up.
- I also believe that the descriptions for the templates should match what is in the mock-up
- The "Server is offline" background is too large/tall on first open.
![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/17635266/41e34238-608b-11e6-8240-14898e89c321.png)

**Comment by hermwong** [comment]
All feedback items above have been broken down to their own separate issues, so it'll be easier for us to track them and also easier for us to have atomic commits.
