### ISSUE TITLE
i cant understand where to make change and where i can see that changes

### ISSUE THREAD

**Issue by priyanka245696** [phonegap/phonegap-app-desktop#685]

**Comment by surajpindoria** [comment]
All of the files for your app are inside the `www` directory. In order to preview the app and see changes, you will need to use either:

1. [Browser](http://docs.phonegap.com/references/browser-support/)
2. [PhoneGap Developer App](http://docs.phonegap.com/references/developer-app/)

When you make changes to any of the files in that directory, the preview will update to use the latest code.

**Comment by surajpindoria** [comment]
Going to close this due to inactivity.
