### ISSUE TITLE
Removing project from disk while app is closed does not update localStorage

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/phonegap-app-desktop#743]
With the app closed, remove a project that was previously displayed in the project list. If you then try to recreate the project with the same location and name you will get a project creation error:

> The chosen folder already contains a PhoneGap project. Please select a different folder.

localStorage will still contain a reference to the old project, we need to come up with a way to check `localStorage.projects` on startup to make sure the projects are still there.

**Comment by hermwong** [comment]
The issue is probably in the [`getProjects`](https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/local-storage.js#L59) method in `local-storage.js`, it's supposed to check for missing projects and remove them from the `localStorage`.

It does this by tracking the an array of missing projects in `global.missing` which is set by the [`missingId`](https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/local-storage.js#L88) method.

The call to [`removeMissingProjects`](https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/local-storage.js#L83) is supposed to remove the projects with IDs that correspond to the `global.missing` array.

**Comment by surajpindoria** [comment]
Cool, thanks

**Comment by surajpindoria** [comment]
No longer reproducible. Closing.
