### ISSUE TITLE
PhoneGap Desktop opening the console with an error when starting 

### ISSUE THREAD

**Issue by GaelMarin** [phonegap/phonegap-app-desktop#749]
### PhoneGap Desktop version
Latest

### Computer OS version
Windows 10

### Network Type (home/corporate)
Home

### Is your network using a proxy?
No

### Are you using VMs on your computer?
No

#### Error messages
http://localhost:35729/livereload.js Failed to load resource: net::ERR_CONNECTION_REFUSED
VM592:1 debugMode: true 
utils.js:63 setDebugFlag - debug passed in: true
analytics.js:16 usage flag: false
analytics.js:17 debug flag: true
VM595:1 found
auto-updater.js:11 update URL: https://raw.githubusercontent.com/phonegap/phonegap-app-desktop/update-check/package.json
auto-updater.js:12 server: 0.4.2 client: 0.4.2

I always have this error when I launch PhoneGap Desktop, any advices to resolve it ?

Thanks in advance !

**Comment by surajpindoria** [comment]
Hi @GaelMarin,

This error does not affect the app while it is in use. We use `livereload.js` while we are developing and it requires a different workflow to load that resource. The last release we uploaded the wrong builds for Windows which displays the console, I have since uploaded the correct builds. If you want to remove the console you can download the new builds from the link below.

https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.4.2

**Comment by GaelMarin** [comment]
Thank you Suraj, I thought I did something bad in my configuration or something ... haha
