### ISSUE TITLE
Add analytics to track serve event

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-desktop#770]
Ideally we should track the serve target.

- serve to browser
- serve to mobile device

**Comment by hermwong** [comment]
It looks like the Desktop app doesn't have a way to differentiate which client is receiving the served content. The Desktop app simply creates a server and allows the user to connect (dev app or browser) via the server's IP address.

@surajpindoria and I thought that we might be able to get around the issue by possibly piggybacking off of the CLI's analytics by using a target parameter, but since the PG-CLI is used as module, the CLI analytics are bypassed when the CLI's features are invoked from the Desktop app. This also prevents duplicate analytics; for example when a project is created - it doesn't get tracked in both the Desktop App and CLI analytics.

**Comment by filmaj** [comment]
Could we get the server to do some user agent parsing (gasp) to determine the target?

**Comment by surajpindoria** [comment]
We are already doing this in `connect-phonegap` so we do know what device is connecting there. I am going to play around with firing an event when the browser connects and catching that in the desktop app.

**Comment by surajpindoria** [comment]
I have updated `connect-phonegap` to fire an event when a device connects. Right now we aren't specifying the platform (Android, iOS...) because the current user agent parsing is pretty frail and I don't trust it. Down the line we can look into updating the dev app to pass platform information so we can more reliably track this info.

https://github.com/phonegap/connect-phonegap/issues/185
