### ISSUE TITLE
Project Create Failed with Code 1

### ISSUE THREAD

**Issue by Lukenickerson** [phonegap/phonegap-app-desktop#772]
## Issue

I am getting the error message "Project create failed with code 1" when using an ID that has a dash (`-`)  on Windows 10, with PhoneGap v0.4.3.

![image](https://cloud.githubusercontent.com/assets/3942453/22805492/cf84ec06-eeeb-11e6-8e7b-cd9d0a80c099.png)

_Work-around:_ I was able to proceed and create a project by not using a dash (-) in the ID field. I was using something like `com.domain.my-project`, and changed it to `com.domain.myproject`. 

_Expected behavior:_ I assume that if dashes are not permitted, "Code 1" should be replaced with a proper error message informing the user about what they should change.

This appears to have the same error message and code as #750 , but probably a different underlying cause since that issue was supposedly fixed in 0.4.3.

### PhoneGap Desktop version
0.4.3
### Computer OS version
Windows 10
### Network Type (home/corporate)
homw
### Is your network using a proxy?
no
### Are you using VMs on your computer?
not at the moment
### Do you have multiple network adapters (or virtual network adapters)?
no
### Are you using VPN?
no

### Expected Behaviour

If dashes are not permitted, "Code 1" should be replaced with a proper error message informing the user about what they should change. If dashes _are_ allowed, then there is some other bug that is causing this.

### Actual Behaviour

Error message: 
> Project create failed with code 1

### Steps to Reproduce 

1. Open PhoneGap app
1.  Click "+" button on left
1. Select "Blank" and click Next
1. Select a Local path and enter a Name
1. Enter an ID with a space in the name (like `com.domain.my-project`)
1. Click Create project

#### Error messages

> Project create failed with code 1

**Comment by surajpindoria** [comment]
Hi @Lukenickerson,

You are correct that PhoneGap project IDs do not support the dash. So that is the reason you are seeing this error.

I do agree with you about having better error messages reported back to the user. I have thought about this a few times but the way we are currently using PhoneGap in the desktop app, there isn't a good way to see what the actual error is. Hence why we have the generic error code 1. I will definitely continue looking into this and hopefully we will be able to find a solution for it.

**Comment by ktecho** [comment]
Any way to see a log of what's happening? I got this error without the dash.

**Comment by ragcsalo** [comment]
Same error here... Also tried to uninstall, then install previous versions... And installed Node.js again. But still getting the error message... Very annoying! :-(

**Comment by surajpindoria** [comment]
@ktecho and @ragcsalo,

Can you please answer the System Configuration questions from above so we can better help you out with your project creation issues.

**Comment by ragcsalo** [comment]
**System Configuration**
PhoneGap Desktop version: 0.4.3
Computer OS version: Windows 7 Pro SP1
Network Type (home/corporate): home
Is your network using a proxy? no
Are you using VMs on your computer? VMware and Virtualbox
Do you have multiple network adapters (or virtual network adapters)? yes
Are you using VPN? no

**Expected Behaviour:**
project created

**Actual Behaviour:**
Error message: Project create failed with code 1

**Steps to Reproduce**
Open PhoneGap app
Click "+" button on left
Select "Blank" and click Next
Select a Local path and enter a Name
Enter an ID with a space in the name (like com.domain.my-project)
Click Create project
Error message: Project create failed with code 1

**Comment by surajpindoria** [comment]
@ragcsalo Can you try without the space or dash in the ID. I believe that spaces are not allowed as well.

**Comment by ragcsalo** [comment]
Oh, no, there was no space nor dash, I just copied it from the previous post.
Project name was "Tesztelek", ID was "com.benkesmith.tesztelek"

There was a previous Node.js installation on my machine (I was using it with Cordova for Android), so I uninstalled Node.js and also PhoneGap Desktop, then installed PhoneGap Desktop again... This time my PATH was not modified, but still didn't work. Then I added the installation path of node.js manually (C:\ProgramData\Adobe\PhoneGap\npm\bin) but still nothing changed.

I guess the error has something to do with Node.js, but I can't figure out how.... :-/

**Comment by ragcsalo** [comment]
Finally I have a solution:
1) uninstalled node.js and PhoneGap Desktop
2) installed latest node.js
**3) installed PhoneGap CLI**
4) installed PhoneGap Desktop
5) created new project in PhoneGap Desktop successfully :-)

The documentation stated we have to install CLI **OR** Desktop, but it seems we have to install both... :-)

**Comment by surajpindoria** [comment]
Glad you were able to get it working @ragcsalo. That should not be the case where you need node/pg-cli installed for the desktop app to work, I will look into this further.

**Comment by ragcsalo** [comment]
Thanks, Suraj! :-) Now I'm superhappy, I love the PhoneGap desktop & mobile app!!! Realtime designing has never been so easy and efficient... THANKS!! :-)

**Comment by sidhiqe0001** [comment]
I have installed ( on 22nd Feb 2017)

After removing all the old files.

1. Installed latest node.js (v7.6.0)
2. Installed PhoneGap CLI (v6.4.3)
3. Installed PhoneGap Desktop (v0.4.3)

macOS Sierra 10.12.3


Tried the solution mentiond by @ragcsalo  mentioned above. But still not able to create a project (try all the template) in Desktop App. Kindly help me @surajpindoria.

let me know if required any further details.

**Comment by surajpindoria** [comment]
Hi @sidhiqe0001,

Can you please answer the System Configuration questions from above.

**Comment by sidhiqe0001** [comment]
Hello @surajpindoria,
I have attached a screenshot of my System Configuration

(https://cloud.githubusercontent.com/assets/2785958/23247059/dc151202-f9bd-11e6-92fe-5c13a1eda33e.png)


Installed latest node.js (v7.6.0)
Installed PhoneGap CLI (v6.4.3)
Installed PhoneGap Desktop (v0.4.3)

**Comment by surajpindoria** [comment]
Sorry @sidhiqe0001, these are the configuration questions I was referring to:

## _System Configuration_

### Network Type (home/corporate)

### Is your network using a proxy?

### Computer / Network security (firewall / anti-virus / disk encryption)

### Are you using VMs on your computer?

### Do you have multiple network adapters (or virtual network adapters)?

### Are you using VPN?

### Expected Behaviour

### Actual Behaviour

### Steps to Reproduce 

#### Error messages

**Comment by sidhiqe0001** [comment]
System Configuration
**Macbook Pro Mid 2012
macOS - 10.12.3
2.5GHz dual-core Intel Core i5 processor (Turbo Boost up to 3.1GHz) with 3MB L3 cache
2.5GHz 8GB of 1600MHz DDR3 memory
Intel HD graphics**


Network Type (home/corporate)
**Corporate**

Is your network using a proxy?
**No**

Computer / Network security (firewall / anti-virus / disk encryption)
**No**

Are you using VMs on your computer?
**No**

Do you have multiple network adapters (or virtual network adapters)?
**No**


Are you using VPN?
**No**

Expected Behaviour
**Create New framework7 project ( i try other project also, that also not working)**


Actual Behaviour
Project Create Failed with Code 1


Steps to Reproduce
**open PhoneGap Desktop (v0.4.3)
Create new phonegap project
Local Path - selected desktop as location
Name - testApp
ID - com.company.testApp**

Error messages
**Project Create Failed with Code 1**

**Comment by GreatDayDan** [comment]
Let me throw my hat into the ring...
I am having the same issue.
System Configuration
Windows 10, generic PC, 3.2MHz(?) i7, 16GB, AMD graphics

Network Type (home/corporate)
home

Is your network using a proxy?
no

Computer / Network security (firewall / anti-virus / disk encryption)
Sophos Home

Are you using VMs on your computer?
no

Do you have multiple network adapters (or virtual network adapters)?
![image](https://cloud.githubusercontent.com/assets/4508458/23410710/aff25c3a-fd95-11e6-8329-c4006eb1981d.png)

Are you using VPN?
no
Expected Behaviour
Create the subfolders, build & run an app.

Actual Behaviour
No folders created.

Steps to Reproduce
Follow the steps hereL http://docs.phonegap.com/getting-started/3-create-your-app/desktop/


Error messages
Project Create Failed with Code 1.

**Comment by surajpindoria** [comment]
Hey @ragcsalo & @GreatDayDan,

I am looking into the issue of needing node/phonegap installed on Windows for the desktop app. Can you answer a few follow up questions for me:
1. Are you installing the app using the [installer](https://github.com/phonegap/phonegap-app-desktop/releases/download/0.4.3/PhoneGapSetup-win32.exe) or [zip](https://github.com/phonegap/phonegap-app-desktop/releases/download/0.4.3/PhoneGap-Desktop-Beta-0.4.3-win.zip)
1. In your command prompt can you navigate to the apps installed location, `<desktop-app>/resources/app.asar.unpacked/bin/` and attempt to run `./node.exe -v`

**Comment by GreatDayDan** [comment]
I used the installer for both.

C:\Program Files (x86)\Adobe\PhoneGap\PhoneGap
Desktop\resources\app.asar.unpacked\bin>node.exe -v
v6.3.1

Now that is odd. I installed node.js 7. I used node-v7.6.0-x64.msi.

Good Morning!

Cya...Dan'l
_________________________________________
Every day with Jesus is a Great <http://www.GreatDayDan.com>! day,
           and He loves you!

**Comment by surajpindoria** [comment]
@GreatDayDan,

Don't worry, this is expected! We bundle a version of node with the desktop app for those that do not have it installed. I just wanted to check that your bundled version is executable.

**Comment by acidjazz** [comment]
i get this error no matter what character i put in any field, i am unable to create a project in phonegap

**Comment by surajpindoria** [comment]
We have just released a new version of the app, 0.4.4, that should display a more helpful error message than the one above. Please try that out and see if it provides any more information.

**Comment by julian71** [comment]
I have the same problem after upgrading my macbook from sierra to highSierra but i was doing step by step same with @ragcsalo doing and success.. now i can continued my project, thanks
