### ISSUE TITLE
PhoneGap Mobile: Cannot connect to any server but the one at my house. 

### ISSUE THREAD

**Issue by Pirouzm** [phonegap/phonegap-app-desktop#797]

**Comment by surajpindoria** [comment]
So you are able to connect at your home, but if you go somewhere else and try you are unable to connect? Could you also provide the information listed above.

**Comment by Pirouzm** [comment]
And in regard to your question, yes- I am able to connect at my home, but if I go somewhere else and try, say if I were to work on an app at a cafe or at my college, I would be faced with error messages and would not get anywhere.

**Comment by surajpindoria** [comment]
This may be due to how the cafe or your college have set up their network. Some networks have additional security features or lock down peer to peer connections which would cause the connection to fail. Unfortunately there isn't much that can be done to remedy these cases. If you find yourself in another situation where you cannot connect you can try using your browser to preview the app if that works for your needs.

Going to close this out.

**Comment by Pirouzm** [comment]
I see. Thank you for looking into this regardless.
