### ISSUE TITLE
Opted out of telementry[turn telemetry on--BUT HOW??]

### ISSUE THREAD

**Issue by shaunVB** [phonegap/phonegap-app-desktop#814]

**Comment by surajpindoria** [comment]
Hi @shaunVB,

Where are you seeing this error from? And can you fill out the information above so we can better debug this?

**Comment by shaunVB** [comment]
First thanks for responding 
Please refer attached screenshot
![issue](https://user-images.githubusercontent.com/29680446/27742143-3543a26e-5dd5-11e7-9f99-92485be0d2ab.PNG)

As it says : You have opted out of telemetry :to hange this run cordova telemetry on
So I had to use CLI interface but it would be easy with desktop , so please help.

**Comment by surajpindoria** [comment]
The warning about telemetry can be safely ignored, I have also submitted a fix that should remove this from future versions of the app. The real problem here is with the cordova-fetch error, can you provide answers to the following to help us with debugging:

1. PhoneGap Desktop version / PhoneGap CLI version
1. PhoneGap Mobile App version
1. Mobile devices & Mobile OS version
1. Computer OS version
1. network type (home/corporate)
1. is your network using a proxy?
1. computer / network security (firewall / anti-virus / disk encryption)
1. are you using VMs on your computer?
1. do you have multiple network adapters (or virtual network adapters)
1. are you using VPN?
