### ISSUE TITLE
Desktop app is totally incompatible with grunt watch. Freezes immediately on watch run.

### ISSUE THREAD

**Issue by distinctdan** [phonegap/phonegap-app-desktop#836]
### PhoneGap Desktop version
4.5
### PhoneGap Mobile App version
N/A
### Mobile devices & Mobile OS version
N/A
### Computer OS version
Macbook pro running El Capitan v10.11.6
### Network Type (home/corporate)
home
### Is your network using a proxy?
no
### Computer / Network security (firewall / anti-virus / disk encryption)
Avast AV, no disk encryption
### Are you using VMs on your computer?
No
### Do you have multiple network adapters (or virtual network adapters)?
No
### Are you using VPN?
No
### Steps to Reproduce 
I'm using typescript and less in my project. When I save a file, I've got grunt watch set up to delete the old files in the phonegap dir and rebuild the project, outputting the new files to the right place. However, whenever grunt watch runs, phonegap desktop totally freezes up, stops working, and I have to force kill it. It's very frustrating. For now, I've stopped using phonegap desktop and instead am running a little node server and manually loading cordova.js.
#### Error messages
The bottom bar of phonegap turns orange and there's an error `watch /my/app/path/www/my/dirs` ENOI...`. I think it's a ENOENT error, but it's cut off.

**Comment by hermwong** [comment]
Hi @distinctdan,

Did this issue happen for you when you were using older versions (0.4.4 or older) of the PhoneGap Desktop App?

The Desktop App has a file watcher on for the `config.xml` so that it updates any changes made to a project's version, id or name to the PhoneGap Desktop's UI.

My initial guess is that the delete process of your grunt watch is causing an issue with the PhoneGap Desktop App's file watcher since you're deleting all of the project files and rebuilding which is causing the PhoneGap Desktop App's watcher on the `config.xml` to throw an `ENOENT` (file or directory not found) error.

**Comment by distinctdan** [comment]
It did happen occasionally on previous versions, but it wasn't that often, so I was usually fine. I do like using that app since it's convenient, I can look into maybe overwriting that file instead of deleting it, although it would be nice if the app didn't crash either.

**Comment by distinctdan** [comment]
Thanks for the info btw.

**Comment by hermwong** [comment]
Another potential work around would be to stop PhoneGap Desktop's server by when your initiate an update through your grunt watch and then restart the PhoneGap Desktop's server once your rebuild is complete.

**Comment by distinctdan** [comment]
Actually, I just double checked and my grunt task only modifies the www directory, so it can't be the config file. The error path that phonegap shows at the bottom points to somewhere in my lib directory inside my app inside the www folder, which holds things like jquery.
