### ISSUE TITLE
downloading0.4.5 triggers anti virus scanner

### ISSUE THREAD

**Issue by Annuther** [phonegap/phonegap-app-desktop#837]
#### Error messages

We are experiencing a Network Failure" error when downloading the latest version of Phonegap (0.4.5) We are currently installed with 0.4.4 which is working fine (apart from the fact that it never shows the app icon in the4 interface no matter where we place the app icon.png file - this has been the case since the last update  - but we can live with this minor issue. Today the issue is that our virus software informs us that there is a virus detected during the download process so the package download always fails. We've tried the 32 bit zip and the exe versions  - both flag up an error with Avast Anti Virus. Until fixed we'll just continue using 0.4.4.

p.s. we have a virtualbox installed but its not being used with phonegap and is disbaled -though we notice that we now get 3 IP addresses showing in the green bar at the bottom of phonegap desktop - this is not an issue and we can use PG as expected.

See Error Message 👍 
![error-dialog](https://user-images.githubusercontent.com/18668429/28998404-214a4894-7a22-11e7-814d-0eedbd901579.png)

**Comment by DaveBolt** [comment]
As of 02:00 on 7 August BST, AVG and Avast were both blocking downloading this file.

Just tried again at 11:30 on 7 August and both **AVG and Avast are now happy** with the Windows zip and exe installers.

Both AVG and Avast have a way to submit a file as a false positive. I was unable to do this from AVG because it told me the file had been put in Quarantine where the option is available, but the file wasn't. Hopefully they will fix this.

It is also possible for the publisher to submit a newly released file to them so they can add it to their 'good repute' list early.

The anti-virus vendors are getting quite cautious about 'new' programs they have not seen before. I have had to exclude my compiler output directory from scans because otherwise I can't run the new program for 15-20 seconds while AVG checks it's reputation.

**Comment by surajpindoria** [comment]
Hi @Annuther & @DaveBolt,

We have been aware of this issue for the last few releases. We had to update how we preform the installation on Windows due to some new features that we added which is in turn causing the issue. I have been working recently to get the Desktop App officially signed with Adobe certs and hopefully this will resolve the issue.

**Comment by Annuther** [comment]
thanks for the update surajpindoria
