### ISSUE TITLE
Phonegap ENOENT error on ##phonegap desktop version

### ISSUE THREAD

**Issue by abcapqr** [phonegap/phonegap-app-desktop#840]
![untitled](https://user-images.githubusercontent.com/30899009/29169303-0be8ebc2-7df1-11e7-9b8d-f9dc016e7913.png)

**Comment by hermwong** [comment]
Can you fill out the info below to help us debug the issue.

## _System Configuration_

### PhoneGap Desktop version

### PhoneGap Mobile App version

### Mobile devices & Mobile OS version

### Computer OS version

### Network Type (home/corporate)

### Is your network using a proxy?

### Computer / Network security (firewall / anti-virus / disk encryption)

### Are you using VMs on your computer?

### Do you have multiple network adapters (or virtual network adapters)?

### Are you using VPN?

### Expected Behaviour

### Actual Behaviour

### Steps to Reproduce 

#### Error messages

**Comment by rodolfolp** [comment]
Hi I have in my PC multiple netwirk adapters, and VMs, I use Genimotion in it.
I cant use Phone Gag.
This is the image
![error](https://user-images.githubusercontent.com/5630226/29255111-8bef1a78-805b-11e7-8d29-cddd1bdbfab2.JPG)
Do you can help me?
I want begin to use Phone Gap
Thanks

**Comment by hermwong** [comment]
Did you install PhoneGap Desktop using the `.exe` installer or from the `.zip` files?

**Comment by rodolfolp** [comment]
Hi Herm
Thanks by your reply.
I install it from .exe
I have two operative systems, in the first, it works good, but in that i
use, dont work
I need that works in the operative system that i use
I have installed Android Studio, and node.js,
Before, i had installed VMSMachine Virtual Box. I quit it now, But the
problems go.
Do you can help me?
Thanks
By

2017-08-14 11:41 GMT-06:00 Herm Wong <notifications@github.com>:

**Comment by hermwong** [comment]
Can you check to see if you're running the PhoneGap Desktop App as an administrator and also check to see if you have permissions to read/write into the folder that you are trying to create the project.

**Comment by rodolfolp** [comment]
Hi, yes i have the adminstrator rights, i unistall node.js of other
instalation but still the problem goes.
do you know what can be?
Thanks

2017-08-14 15:42 GMT-06:00 Herm Wong <notifications@github.com>:

**Comment by hermwong** [comment]
Usually this error occurs due to a permissions issue or if the computer doesn't have node installed.

Could you see if the solutions suggested in this [thread](https://github.com/phonegap/phonegap-app-desktop/issues/799) help?

**Comment by aiikendoit** [comment]
I've been there with this kind of error, I figure out that Node.js must be back to default.
So what i did, I go to Control Panel and look for node.js, then don't uninstall it, just click repair, and everything will roll back to defaults.

**Comment by rodolfolp** [comment]
Thanks Kenneth, i go try and notice you

By

Rod

2017-10-23 18:19 GMT-06:00 Kenneth Israel <notifications@github.com>:

**Comment by rodolfolp** [comment]
I thing what the problem is that my oprative system im not the
administrator.
Look the image i sent you
There is my name, and other name of administrator
Can you see?
My name is Rodolfo
I tried of put my system how administrator but i cant do it
Im in the second disk
My pc has two disk
Im in C:, but in the second disk
Do you can help me?
Thanks


2017-10-24 17:33 GMT-06:00 rodolfolopezp . <rodolopa@gmail.com>:

**Comment by qesterx** [comment]
Same error here (Windows 10), desktop version (.exe), I tried to:
- install node.js
- uninstall node.js
- installing phonegap on c:
- installing phonegap on d:
- installing xamp (tought maybe localhost problem)
- uninstall phonegap

Still not working, but:
- I install phonegap on my LOCAL machine, BUT, I have VMWARE installed (but NOT using PhoneGap on a virtual machine), is an vmware installation causing this error?

- I also had tried ionic, but that also did not run, but phonegap looks easier to use because html and css knowledge, so I want to stick with phonegap.

Everything is updated to the latest version.

Any suggestions?

Thank you!

**Comment by rodolfolp** [comment]
Hi, Do you resolve the problem?
Thanks

**Comment by rodolfolp** [comment]
Yes, I resolve iit now
Thanks

**Comment by Astet1208** [comment]
How did you fix it???

i am getting this error:
Creating a new cordova project 
Error: Unhandled error. ('\u001b[1m\u001b[31m Error from Cordova Fetch: Error: cmd: Command failed with exit code ENOENT')

**Comment by 2wyse** [comment]
> 
![1574040040264619790317](https://user-images.githubusercontent.com/41148644/69017922-16cf5c00-09aa-11ea-91e9-15acf3a992e5.jpg)
How can I resolve it pls

**Comment by 2wyse** [comment]
Help me out
