### ISSUE TITLE
Screen goes white after load?

### ISSUE THREAD

**Issue by Tr0j4n9** [phonegap/phonegap-app-desktop#847]
When I run PhoneGap,

![image](https://user-images.githubusercontent.com/30397502/29748081-afcb3898-8ac2-11e7-9e34-82145ed11911.png)

It loads:
![image](https://user-images.githubusercontent.com/30397502/29748087-d57cf48c-8ac2-11e7-8afe-9acefe00cc77.png)

After a few seconds: 
The screen goes white:
![image](https://user-images.githubusercontent.com/30397502/29748089-eb9d6396-8ac2-11e7-8fdb-5e13fb20181e.png)

Does anyone know why?
(Sorry if duplicate)

EDIT: If im not connected to the internet it will take longer to go white.

**Comment by hermwong** [comment]
Please provide the following info:

## _System Configuration_

### PhoneGap Desktop version

### PhoneGap Mobile App version

### Mobile devices & Mobile OS version

### Computer OS version

### Network Type (home/corporate)

### Is your network using a proxy?

### Computer / Network security (firewall / anti-virus / disk encryption)

### Are you using VMs on your computer?

### Do you have multiple network adapters (or virtual network adapters)?

### Are you using VPN?

### Expected Behaviour

### Actual Behaviour

### Steps to Reproduce 

#### Error messages

**Comment by SalvaMG** [comment]
Hi ! I have exactly the same issue :/ When i launch the Phonegap Desktop App, the screen goes white.

Here is my system configuration :

PhoneGap Desktop version : 0.4.5

PhoneGap Mobile App version : 1.8.2

Mobile devices & Mobile OS version

Computer OS version : MacOS : 10.13.1

Network Type (home/corporate) : Home

Is your network using a proxy? : No

Computer / Network security (firewall / anti-virus / disk encryption) : No using MacOS

Are you using VMs on your computer? : No

Do you have multiple network adapters (or virtual network adapters)? No

Are you using VPN? No

Expected Behaviour : Show home screen to add or create new project

Actual Behaviour : When i launch the desktop app, it loads a few seconds then it goes white

Steps to Reproduce : Just launch the app and wait ...

Error messages :  No messages, just a white screen :(

Thanks for your help !

**Comment by neverhood311** [comment]
I have the exact same issue, but in Windows 10.

PhoneGap Desktop version: **0.4.5**

PhoneGap Mobile App version: **1.8.2**

Mobile devices & Mobile OS version: **iPhone 5S, iOS 11.1**

Computer OS version: **Windows 10, Version 1709, OS Build 16299.64**

Network Type (home/corporate): **Home**

Is your network using a proxy?: **No**

Computer / Network security (firewall / anti-virus / disk encryption): **Windows Defender**

Are you using VMs on your computer?: **No**

Do you have multiple network adapters (or virtual network adapters)?: **No**

Are you using VPN?: **No**

Expected Behavior: **Create a project, run it.**

Actual Behavior: **I can sometimes create a project or click on it, but the screen turns white. The file menu is available, but none of the options do anything when clicked.**

Steps to Reproduce: **Start the program and do anything...or nothing. It doesn't take much.**

Error messages: **None**

**Comment by SalvaMG** [comment]
Anyone ? Please, i'm stuck and can't test my app without it :(

**Comment by surajpindoria** [comment]
@SalvaMG,

Have you tried using the PhoneGap CLI? You can use the same functionality to test your app using the `phonegap serve` command.

**Comment by paulcitcom** [comment]
Your solution to the problem is to not use the program? 😂 For anyone else having this I was able to get the program to load by right clicking the link and running as admin. Hope this helps.

**Comment by hermwong** [comment]
Just a few questions that may help.

1. How did you install the Desktop App (zip or exe)?
2. Do you have node installed?
3. Are you running the Desktop App as Administrator?
4. Did you have an internet connection the first time you ran the Desktop App?

**Comment by fenkner** [comment]
I just went through the "Get Started" page since I'm evaluating PhoneGap as a first time user and I'm having the same problem.  I just installed it onto Windows 10 using the setup exe file.  I started the app, created a hello world project and installed the PhoneGap mobile app.  When the project was created I saw that the server was running but before I could do anything the page went white.  None of the menu items in the app work either.

**Comment by and3rsonsousa** [comment]
Same problem here. It opens normally at the first run, but if I make any change the page goes white.

**Comment by rpacheco-blazquez** [comment]
Same here

**Comment by jon64digital** [comment]
Me too. Judging by the date son this thread I assume nobody is attempting to fix this, which means I'm going to have to ditch the idea of using Phonegap before I've got through the Getting Started Tutorial :(

**Comment by paulcitcom** [comment]
it was a permissions problem for me. caused my my webroot security software

**Comment by artabria** [comment]
Me too... anyone find a solution for this issue?

Thanx in advance!

**Comment by tiagoagre** [comment]
Windows:
Solved this issue by going to PhoneGap installation folder, usually located here:
C:\Program Files (x86)\Adobe\PhoneGap\PhoneGap Desktop
Right click "PhoneGap.exe" -> "Compatibility" Tab -> "Run this program..." -> Select "Windows 8" or "Windows 7"

**Comment by locogrid** [comment]
Tried compatibility setting in windows7, tried running as admin , tried deleting phonegap from cli, tried uninstalling and installing desktop app - nothing worked
