### ISSUE TITLE
Issue opening existing projects

### ISSUE THREAD

**Issue by Enpega** [phonegap/phonegap-app-desktop#867]

**Comment by Enpega** [comment]
When I try to open an existing project in Phonegap Desktop, nothing happens. The same when I drag the folder into de application. When I try to open any other folder, a "missing config.xml" appears (as its supposed). 
Something similar happens when creating new project. It doesn't appear in the projects list, although the server starts.
I tried a workaround by deleting the .cordova and LocalStorage folders, but the next day it showed the same behaviour again.

What can I do?
Thanks.

**Comment by hermwong** [comment]
Can you provide the following info:

## _System Configuration_

### PhoneGap Desktop version

### PhoneGap Mobile App version

### Mobile devices & Mobile OS version

### Computer OS version

### Network Type (home/corporate)

### Is your network using a proxy?

### Computer / Network security (firewall / anti-virus / disk encryption)

### Are you using VMs on your computer?

### Do you have multiple network adapters (or virtual network adapters)?

### Are you using VPN?

### Expected Behaviour

### Actual Behaviour

### Steps to Reproduce 

#### Error messages

**Comment by Enpega** [comment]
PhoneGap Desktop: 0.4.5
PhoneGap Mobile App: N/A
Mobile devices & Mobile OS version: N/A
Computer OS: Windows 10 Home Version 1703
Network type: Home
Proxy: No
Computer security: Defender
VMs: No
Multiple network adapters: No
VPN: No
Expected behaviour: Opening PhoneGap and seeing all projects loaded in window. Same thing creating a new one.
Actual behaivour: Opening PhoneGap and seeing empty window. Creating a new project shows nothing also.
Error messages: No messages appear.

**Comment by hermwong** [comment]
Thanks, I'll try to see if I can reproduce the issue.

Are you running PhoneGap Desktop as Administrator?

**Comment by Enpega** [comment]
Yes I am

**Comment by Enpega** [comment]
UPDATE: If I delete the files file__0.localstorage and file__0.localstorage-journal I'm able to create new projects, not opening existing ones.

**Comment by hermwong** [comment]
Which directory were those files located?

**Comment by milehighjustin** [comment]
if you open it, then go to the gear for settings and hit save, the project will start being served up and it will even notify you of the address at the bottom and stuff. Workaround but it works i suppose.

**Comment by milehighjustin** [comment]
(it wont show up in the list when you do that)

**Comment by Enpega** [comment]
It works. The project is served, although not showing in the window.
For the time being, it'll do.

Thank you very much.

**Comment by milehighjustin** [comment]
Nice. I'm trying my damn desk to figure out what makes it do this, but I just can't. I feel like it happens after a build maybe, so maybe a build artifact somewhere? Oh and once you get going with the workaround I detailed above, it becomes incredibly difficult to open a second project up. I think because the list is gone. In those instances I just use Cordova-server.

**Comment by Enpega** [comment]
Sorry for the delay. I'm just working on one project basis until it gets fixed. It's not really annoying me.
Thank you for all your help.
